fixed merge issues
chaaf3/CS555-C-Project pull request #17
Opened 2023-03-23 21:26 UTC by haujla1

tested and works with most recent

2023-03-23 21:42 UTC, venkatanna9 commented on backend/data/projects.js
> +  if (!currentProject.equipmentRequired) {
You can initialize the empty arrays for these fields when creating a project in createProject()

2023-03-23 21:42 UTC, venkatanna9 commented on backend/data/projects.js
> +const updateEquipmentDelivered = async (projectId, items) => {
Rename items to deliveredItems for clarity

2023-03-23 21:43 UTC, venkatanna9 requested changes
View comments

2023-03-23 21:54 UTC, venkatanna9 approved these changes

2023-03-24 02:39 UTC, chaaf3 approved these changes

2023-03-24 02:39 UTC, merged