Adding login and signup functionality in backend
chaaf3/CS555-C-Project pull request #21
Opened 2023-04-05 18:38 UTC by AughdonBreslin

2023-04-05 23:12 UTC, venkatanna9 commented on backend/validation.js
> +  // https://www.geeksforgeeks.org/check-if-a-string-contains-uppercase-lowercase-special-characters-and-numeric-values/#:~:text=Traverse%20the%20string%20character%20by,it%20is%20a%20lowercase%20let
Love how you included a link as reference

2023-04-06 00:03 UTC, venkatanna9 requested changes

2023-04-06 00:04 UTC, venkatanna9 approved these changes

2023-04-06 00:24 UTC, chaaf3 approved these changes

2023-04-06 01:28 UTC, merged